/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file delete.gif */
extern const unsigned char delete_gif[];

/* created by reswrap from file new.gif */
extern const unsigned char new_gif[];

extern const unsigned char broom_gif[];