/* Generated by reswrap version 4.0.0 */

/* created by reswrap from file delete_gif.gif */
extern const unsigned char delete_gif[];

/* created by reswrap from file new_gif.gif */
extern const unsigned char new_gif[];
